# Generated by Django 4.0.4 on 2022-05-08 20:14

import accounts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_influencer', models.BooleanField(default=False)),
                ('is_brand', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('category_type', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('instagram_id', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('short_description', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(upload_to='brand_images/%Y/%m/')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('channel_name', models.CharField(max_length=100)),
                ('youtube_id', models.CharField(max_length=100)),
                ('instagram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('category_type', models.CharField(choices=[('Autos & Vehicles', 'Autos & Vehicles'), ('Comedy', 'Comedy'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Film & Animation', 'Film & Animation'), ('Gaming', 'Gaming'), ('Howto & Style', 'Howto & Style'), ('Music', 'Music'), ('News & Politics', 'News & Politics'), ('Nonprofits & Activisms', 'Nonprofits & Activisms'), ('People & Blogs', 'People & Blogs'), ('Pets & Animals', 'Pets & Animals'), ('Science & Technology', 'Science & Technology'), ('Travel & Events', 'Travel & Events'), ('Sports', 'Sports')], max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='influencer_images/%Y/%m/')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
