# Generated by Django 4.0.4 on 2022-05-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_brand_full_name_alter_brand_category_type'),
        ('accounts', '0002_user_name'),
    ]

    operations = [
    ]
