# Generated by Django 4.0.3 on 2022-03-20 15:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_influencer_channel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('category_type', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('established_date', models.DateField()),
                ('instagram_id', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('short_description', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(upload_to='brand_images/%Y/%m/')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='influencer',
            name='profile_photo',
            field=models.ImageField(upload_to='influencer_images/%Y/%m/'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
