# Generated by Django 4.0.3 on 2022-03-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='city',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='youtuber',
            old_name='name',
            new_name='influencer_name',
        ),
        migrations.RenameField(
            model_name='youtuber',
            old_name='photo',
            new_name='profile_photo',
        ),
        migrations.RenameField(
            model_name='youtuber',
            old_name='channel_id',
            new_name='youtube_channel_id',
        ),
        migrations.RemoveField(
            model_name='youtuber',
            name='age',
        ),
    ]
