# Generated by Django 4.0.3 on 2022-03-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to='images/%Y/%m/'),
            preserve_default=False,
        ),
    ]
