# Generated by Django 4.0.3 on 2022-03-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_influencer_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='channel_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
