# Generated by Django 4.0.3 on 2022-03-23 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_brand_alter_influencer_profile_photo_delete_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='established_date',
        ),
    ]
