# Generated by Django 3.1.7 on 2022-04-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220419_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='influencer_images/%Y/%m/'),
        ),
    ]
